version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12.17.0
    working_directory: ~/app

jobs:
  check_branch_name:
    docker:
      - image: circleci/node:12.17.0
    working_directory: ~/app
    steps:
      - run:
          name: fail if the branch name does not start with a valid prefix
          command: |
            branch=$CIRCLE_BRANCH
            if [[ "$branch" =~ ^(dependabot|fix|feature|breaking)/ || "$branch" == 'master' ]]
            then
              echo $branch is a valid name
            else
              echo $branch is not valid because the branch name must match '^(dependabot|fix|feature|breaking)/' or be master
              exit 1
            fi
  test:
    executor: node-executor
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: yarn test:coverage
      - run: yarn build
      - run: cd docs-www && yarn install --non-interactive && yarn build && cd ..
      - run: ls -la
      - run: ls -la node_modules/
      - run: ls -la node_modules/ | grep mime
      - persist_to_workspace:
          root: ~/app
          paths:
            - .git
            - node_modules
            - coverage
  publish_package:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/app
      - run: ls -la
      - run: ls -la node_modules/
      - run: ls -la node_modules/ | grep mime
      - run: npm run clean-dist && npm run gen-mime-types

workflows:
  version: 2
  lint_and_test_and_publish:
    jobs:
      - check_branch_name
      - test:
          requires:
            - check_branch_name
      - publish_package:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - fix/inspect-ci
